services:
  - type: web
    name: shelby-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run prisma:migrate && npm run start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN_CLIENT
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
