// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';
const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const createNoopQueryBuilder = () => ({
  select: async () => ({ data: null, error: { message: 'Supabase no está configurado en el entorno actual.' } }),
  insert: async () => ({ data: null, error: { message: 'Supabase no está configurado en el entorno actual.' } }),
  update: async () => ({ data: null, error: { message: 'Supabase no está configurado en el entorno actual.' } }),
  delete: async () => ({ data: null, error: { message: 'Supabase no está configurado en el entorno actual.' } }),
  eq: () => createNoopQueryBuilder(),
  order: () => createNoopQueryBuilder(),
  single: async () => ({ data: null, error: { message: 'Supabase no está configurado en el entorno actual.' } }),
});

const fallbackSupabase = {
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
    signOut: async () => ({ error: null }),
    signInWithPassword: async () => ({ data: { session: null, user: null }, error: { message: 'Supabase no está configurado.' } }),
    signUp: async () => ({ data: { session: null, user: null }, error: { message: 'Supabase no está configurado.' } }),
    verifyOtp: async () => ({ data: { session: null, user: null }, error: { message: 'Supabase no está configurado.' } }),
    signInWithOtp: async () => ({ data: { session: null, user: null }, error: { message: 'Supabase no está configurado.' } }),
    updateUser: async () => ({ data: { user: null }, error: { message: 'Supabase no está configurado.' } }),
  },
  from: () => createNoopQueryBuilder(),
  storage: {
    from: () => ({
      upload: async () => ({ error: { message: 'Supabase no está configurado.' } }),
      getPublicUrl: () => ({ data: { publicUrl: '' } }),
    }),
  },
  functions: {
    invoke: async () => ({ data: null, error: { message: 'Supabase no está configurado.' } }),
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : (fallbackSupabase as any);